entity: property
columns:
  - { name: sal_code, type: string }
  - { name: suburb, type: string }
  - { name: postcode, type: string }
  - { name: period, type: int }
  - { name: median_house_price, type: double }
  - { name: median_unit_price, type: double }
  - { name: median_rent_weekly, type: double }
  - { name: sales_volume, type: int }
